# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6b43c3fb84f9f06ab608ec1d0174643c44f83a9e2699d636930fd274cb81a449f9442a18f7ffee46d1d4493ed280397ad8c9091b30e60507ca3e5714d705c33

test:
  secret_key_base: b9c645969f46b97109a400b3ba42b8b4246d93abfca07fbba1d1a890d8715e92759eb81418470210df213eef1a74ef0518f5d18693d4ffc8a586ae1e89deb835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
